apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./calendar-es.yaml
  - ./calendar-gw.yaml
  - ./webhook-es.yaml
  - ./webhook-gw.yaml
  - ./sensor.yaml
  - ./wftmpl.yaml

configurations:
  - image-transformer-configuration.yaml

images:
  - name: solgate
    newName: quay.io/thoth-station/solgate
    newTag: latest
