apiVersion: v1
kind: Secret
metadata:
    name: solgate-dev-instance
stringData:
    source.creds.yaml: ENC[AES256_GCM,data:8LNogDuVl3Tw3qfv5GGsnmSpOUkYFmcrOR7vBIfJMaLNnvBxJixyz+MC96bQEdD/eMKhqhtThp8tFZDkXbskwdXRs9E6/pLXLCsY5aQosUwLxIR+bNzeqw0cWEjLQaJbN2jkYk3u3yc=,iv:4XbgyYz2cWenXG5YaJtZ2w+jTGm7eBIihSbdjtpa9ww=,tag:RaAxVsJKfdCMz/DVA03iiA==,type:str]
    destination.creds.yaml: ENC[AES256_GCM,data:MOgPyxqDmTD5OdZeS5tEbb8NS3t9194L/obMjl0aY/Q+IRKc3JWlFHxHhpWK81a1Usa03FiDvuWuir7cReP26F/SaPVvXg88n6Ep6l3A5xLuVlW8gWcfi9evFX5M9PdXzXak02JjCkU=,iv:WaOOAnb7xdPIIis/XBlDq3Im47oQMKcOxvQjgrtaBos=,tag:cpuTGDst1TjWzwgw+XeoWg==,type:str]
    config.yaml: |
        alerts_smtp_server: smtp.corp.redhat.com
        alerts_from: solgate-alerts@redhat.com
        alerts_to: tcoufal@redhat.com

        source:
          endpoint_url: https://s3.upshift.redhat.com
          formatter: "{date}/{collection}.{ext}"
          base_path: DH-PLAYPEN/storage/input

        destinations:
          - endpoint_url: https://s3.upshift.redhat.com
            formatter: "{collection}/historic/{date}-{collection}.{ext}"
            base_path: DH-PLAYPEN/storage/output
            unpack: yes

          - endpoint_url: https://s3.upshift.redhat.com
            formatter: "{collection}/latest/full_data.csv"
            base_path: DH-PLAYPEN/storage/output
            unpack: yes

          - endpoint_url: https://s3.upshift.redhat.com
            base_path: DH-PLAYPEN/storage/output
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-16T14:32:26Z'
    mac: ENC[AES256_GCM,data:/jv7GKkOVi1fuNRfU73MSpTgnwJ1oamwAKxxuWqAD4hRE/5gr3AV9y3vDsMNSc8R3izz+GGnUA17jgtbjTQWmxwQjRqNq0B3SlpkxHfPrevh50lQEs8apOm2U2VFE4VOZ2QwmTSbvoqwvfrnkLfCXa2U3dQGlr2hDXt8tAwKojI=,iv:6vPr4nuCZWwqY7Sf/Ix+Yvsc/nPA7kdgiBrtDiP23/A=,tag:Fu1E7Ff2iGBzenPBuPeajg==,type:str]
    pgp:
    -   created_at: '2020-12-18T11:45:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/e/2zdCk+AtiFBg3xS3AoxD2GsmBk7BEkm9T4611Iwk7d
            oRQ+iGrCGJ9Zy8SmYa886ZWaID6/0l5CyYv9bizriZ2qnCXy8q0sQlohVbRgVBme
            UH+mG4evqV2n/wkpWLtCp3kzJLTm9u1vX3Adu+SSLCmRbnIxV8HsptCdxFCNXWFs
            8run3bR9LcXvkEaRyxNlPMgNGdYz26uEEd/cDEt9XKcFz1GlJLL7kBiUIinqeanD
            8u6ZQhTp1cZzeZARzvAbceRvN/RvZNV7fWCWLT9/9irW/lB/nnWFnyyvkLqFNpyy
            70GJKZufMT1+07/1x1UnimEkfsuJr7VAFJ6Dxxs60tJeAcdH8C68higVl+wv4B9T
            X6Fu5MMndEt1mTfAlYlfpTNBC5OfrUOUktnaQUPdVEH78T8FkOj9hVF6jruUjvWR
            5UiJmyHNTrsvaCFCKW8PxAeNYeicDI3mKKDcmtu3iw==
            =ChUf
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2020-12-18T11:45:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5MpUvZdp4z9AQ//bp9MYdvmI+qYqZKOMXFenL4e5OZ39YOcAXKSDA+kPL95
            oghmXLAMQ86EIh5icnk+ok/guHyaedcjvyYx5Ms/hhrQSbM7m/7HQh7xRABlJquD
            LlKuHSiPJ0/bPjgxxf2G/AgtWwBXVxWmFFskvi/csU8gacBOcx6ty/d4Huv7wJ0w
            N2OG68YvPYl/CkmZJ3Qz6LhYnGRXfDs1zdNDSl/x9FfbSYLPgcd6czTurAL6WY/H
            u0wYB7u1eQjdoot2CX5BOAGxIMFWkrAsXohIifgAVcFGK81LlxfFaV3vdAXu1s7A
            BX/dIAFH485bF6nehxX8yNKgiU1CKi+zV+ejNcchebMSTykB9QYb1Ge+HcSnKYm0
            h+RpJxRI1UuhjwZIs96MuGMtp5X28JLxDdy0wG8eHS00TlJMjZLJVdGHxD5abBtb
            VMxUxX1Bdm3XuR+I7+qugnbBNYwtBfxGhhq2QjRVvcgFwlU64Ffe3TE2xoyeAqhw
            QiIVuVZn21xb77HAZOvU5zHxrqqV8ZKTqZEW54TP7yDq01r/A+5YqhS/zKk9kBQi
            Ynf9EpeC1OLJfoZwZIrcBv72fwrEnmdHhF7oCwoiCd2UFnOpm36k6Nta2JlIkI0o
            Uw86zaoG0oQhsjNn2FisghoyquQQuniJY11SoFqfYEx8rwYYHMreKzoxXWUegXTS
            XgELjKCjI1MYzOCUyNPg9PEiZd+qUXmJv5GlSxVTS5M7ghAqiVr3T5ti4Oxlb4vJ
            +BlyuCWCFgKVd9v6fRB5/DJkvC1PiXO033pXAF0n1zg/YKeN+RkjsfotRFLJ8cs=
            =8EhQ
            -----END PGP MESSAGE-----
        fp: A76372D361282028A99F9A47590B857E0288997C
    encrypted_regex: ^(.*.creds.yaml.*)$
    version: 3.6.1
