check:
  - thoth-build
  - thoth-precommit
release:
  - upload-pypi-sesheta

build:
  base-image: registry.access.redhat.com/ubi8/python-38:latest
  registry: quay.io
  registry-org: thoth-station
  registry-project: solgate
  registry-secret: thoth-pusher
