apiVersion: v1
kind: Secret
metadata:
    name: solgate-cost-management
stringData:
    source.creds.yaml: ENC[AES256_GCM,data:oXggp50RsDsmfVMxk2/B23oy0n2Thh5y6YLd6ok0eVwckRQddBiPyN9GHVtiPkmjwiMSn4w3esOHT90RtK8/AGdDNl/FBxMchP0PhZmfjJnJz/XAAzryAZZzl8h89+O671YfQZiezoY=,iv:W+3KoMQJg3qlhARk7PSnmsSg1ZAUYJgdS1FV6hvTF1o=,tag:uqyf2eBpA/s8NhaReJBOCg==,type:str]
    destination.0.creds.yaml: ENC[AES256_GCM,data:+tryrBv27NfBn+T6265gqzT6wcfxtGPcCmTebIaQ11cMMfxGOEJ3/pSxqBVba6NhtbHSI2RqtHhHkbqeT7RCgYPF+PJpB9DtGv0gavLHcpjjZ4cv+pOUrvkba/7AzsmmmNtRcVFtWb8=,iv:F++hpi9KWW17eU1MQws8XWjD0PbxfbWoflGQjFECGok=,tag:2uM8W3VeAg/8lUE3aCAQ7g==,type:str]
    config.yaml: |
        alerts_smtp_server: smtp.corp.redhat.com
        alerts_from: solgate-alerts@redhat.com
        alerts_to: chambrid@redhat.com
        timedelta: 12h

        source:
          endpoint_url: https://s3.amazonaws.com
          base_path: hccm-prod-s3

        destinations:
          - endpoint_url: https://s3.upshift.redhat.com
            base_path: DH-SECURE-COST-MANAGEMENT
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-12T14:22:31Z"
    mac: ENC[AES256_GCM,data:sFeTisUxl24tuPBChKe9WnlJrnJeUI5dT1+HWMS6Pv+5V9D4XXWYGHkgeQV11GmfuX6ikRvKBweslYGZJzADt7UExsNeg/wkk+NXj67E9Lkq8S5NjiRKyQ8lpASbTaWb3kVD/K6rsY9PwjsxI8QgFijM+yvfJUboIzHtpOlD3zg=,iv:xpc9Jp7pChs77WC3jX5auj09EqwHyx05W73zyKmp0Lw=,tag:YbAcIcYsbhsvqRGhSwlTOg==,type:str]
    pgp:
        - created_at: "2021-08-12T14:22:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/eQcDZ1JgU5KU+YOdrPAnIDq0jHUZGEz+ASORT0EvK97C
            vk3/QDTdODkDhR3DE+9l13m+PZUwxYZy/wZHrBkb+IbrypD5wWvsOAPev6aVZ5Kw
            ksWDIkCjLi5LWAhmXX2vDS5jwadu64wYp5ZZWhlG5HxxL1zHEsPMVGQT8yAf/GXb
            0V262JkrAwYlGqMIXsRXWTxEtciDo3E3CW/b4HV+uF2/pUdHeqPdC5no1/X0z9+H
            Of8u9PJgOpeGZaJHXLj7YZ9fh9VwuTpyOn9QqGxvZn1+Y6ZPj+vlYlEuGEr+YWpu
            /F6OqCbbjgfLkUoYQosr6+APXiQQHHxbkJQ7WFyDi9JeAZd7gBZHbpWKT2LL3oWz
            1AkFbyv+U0SdZeb6lVGgzUpaM6owdng3vxNWyjdBI2PgO7kUreUSLbKrj/i0lSi0
            lfUPM2MjG/X0rIcfgT9Yq7THfjIb22Og6J3urqEghg==
            =ZoYO
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
        - created_at: "2021-08-12T14:22:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA5MpUvZdp4z9ARAAFqjqG1SxizinZxjIQbwaW3eVHutx1kv0+EkB6PKpRQO6
            +EpcH83K4yI5qG4sjgecGnECqiSFhCbdmHysVOSRh8Y72qV0xMGyd98P3NvRf3xV
            MSQIBFX8zul6OwxON907QHefOkHM8LDJfItFneSXhNFNfwKm6btsoCtggdzlOXhP
            k0jkuHvVgnHC4mT/UDgD2VlE7JeYOnC0i5is2fcsqYwBi1CpYKUI6xmqU+ndjiVy
            KeLNY5Mu2+ey83UP3AFPIk6rprOrFUcUGjzMrDFXe2T9RlKUcJnQyAQfVSXAfoJW
            A7u0+vzDVv/+UlJDh8fxtDqvUQX8Pxfcgru10HYdc06buxgi5m6aPosvcQ3MeB/H
            v8gcNcF3BYTOoPLEPUvWLplDKCWd/j2eJevt0DrLrO4k8obLghwCvPTfiZED3J/n
            fdoqbsfzTnIGy4Z4tDHtrLjkBQMslr5JYihfEeXJAJmblLaYJYSeWbv+PbLHhVB1
            yGamitqhYs+JWMMQ/RXhqdM6w/UtNmXqbjsm5amhZ5Hht53eKE0IAPkXvooFGJRi
            7RvWb9OWlowyPX3PMgvdprg/W8aejTOdTM1KgMsVl0b8V61S6psUdQo61h/DAIpf
            TuaHpbM1v6G7JVgP1IG455m7zmg0edzM5pALe0YA3SEyvhCL24QosDf/AZQ0VNfS
            5gG7m9TuIjiRS9QEr6esfNG8tKFIxf8ZQKFBOcuuIZu4u8Xy3byEWVFtzX+3D0E9
            AVSiaaCPgFmpaR1Jos9Z5G3kxpp9RI+Go+FZzSd0O8bZD+I1fF0OAA==
            =dTwv
            -----END PGP MESSAGE-----
          fp: A76372D361282028A99F9A47590B857E0288997C
    encrypted_regex: ^(.*.creds.yaml.*)$
    version: 3.7.1
