apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: solgate-mms
  name: solgate-mms
spec:
  schedule: "0 0/6 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: config
          value: solgate-mms
    workflowTemplateRef:
      name: solgate
