apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: solgate-backfill-
spec:
  arguments:
    parameters:
      - name: config
        value:
      - name: split
        value: "5000"
      - name: is-backfill
        value: "true"
  workflowTemplateRef:
    name: solgate
