apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: solgate-usir
  name: solgate-usir
spec:
  schedule: "15 15 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: config
          value: solgate-usir
    workflowTemplateRef:
      name: solgate
